#!/usr/bin/env zsh
http_proxy="http://127.0.0.1:7890"
https_proxy="http://127.0.0.1:7890"

# 避免重复写入：先清旧行
sed -i '' '/^export http_proxy=/d; /^export https_proxy=/d' ~/.zshrc
# 追加新行
echo "export http_proxy=$http_proxy"   >> ~/.zshrc
echo "export https_proxy=$https_proxy" >> ~/.zshrc
echo "Proxy ON -> $http_proxy"
echo "[!] remember to source ~/.zshrc or open a new tab"
